# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuid', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=5000)),
                ('product_type', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=2000)),
                ('image_link', models.URLField(max_length=2000)),
                ('condition', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('price', models.FloatField(default=99999999.99)),
                ('sale_price', models.FloatField(default='')),
                ('brand', models.CharField(max_length=100)),
                ('gtin', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('model_code', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name='Created_date')),
                ('updated_date', models.DateTimeField(verbose_name='updated_date')),
            ],
        ),
    ]
