# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='sku',
        ),
    ]
