# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0002_remove_productdata_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='google_product_category',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
