# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0003_productdata_google_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='sale_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
