# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0004_auto_20170301_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(verbose_name='Created_date')),
                ('updated_date', models.DateTimeField(verbose_name='updated_date')),
            ],
        ),
        migrations.RemoveField(
            model_name='productdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='productdata',
            name='skuid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='productdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productentity.Productdata'),
        ),
    ]
