# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0007_auto_20170302_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productfeed',
            fields=[
                ('product_feed_url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='created_date')),
                ('updated_date', models.DateTimeField(verbose_name='updated_date')),
            ],
        ),
    ]
