# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0008_productfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeed',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='productfeed',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
    ]
