# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productentity', '0009_auto_20170313_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
    ]
